
osci:
	gmake -C example_3_2 -f osci_make
	gmake -C example_3_3 -f osci_make
	gmake -C example_3_4 -f osci_make
	gmake -C example_3_5 -f osci_make
	gmake -C example_4_1 -f osci_make
	gmake -C example_4_2 -f osci_make
	gmake -C example_4_3 -f osci_make
	gmake -C example_4_4 -f osci_make
	gmake -C example_5_1 -f osci_make
	gmake -C example_5_2 -f osci_make



all: osci

clean_osci:
	gmake clean -C example_3_2 -f osci_make
	gmake clean -C example_3_3 -f osci_make
	gmake clean -C example_3_4 -f osci_make
	gmake clean -C example_3_5 -f osci_make
	gmake clean -C example_4_1 -f osci_make
	gmake clean -C example_4_2 -f osci_make
	gmake clean -C example_4_3 -f osci_make
	gmake clean -C example_4_4 -f osci_make
	gmake clean -C example_5_1 -f osci_make
	gmake clean -C example_5_2 -f osci_make
	rm -f user/*.o

clean: clean_osci


